### ISSUE TITLE
espace surnuméraire dans \parencite 

### ISSUE THREAD

**Issue by adadam** [Jean-Baptiste-Camps/biblatex-enc#1]
Lorsque j'utilise \parencite pour la classe book sans numéro de page, il y a un espace surnuméraire avec la prenthèse fermante pour la première occurence.
Lorsqu'il y a un champ url, le problème ne se présente pas.

**Comment by Jean-Baptiste-Camps** [comment]
Le problème était localisé sur le driver `{cite:book}`. C'était une simple histoire d'absence de `%` en fin de ligne... 
Voici une nouvelle version qui corrige le problème (à renommer en enc.bbx) !
[enc.txt](https://github.com/Jean-Baptiste-Camps/biblatex-enc/files/46626/enc.txt)

**Comment by adadam** [comment]
Super merci!
Et un ticket résolu, un!

Le 29 novembre 2015 15:09, Jean-Baptiste-Camps notifications@github.com a
écrit :

> Le problème était localisé sur le driver {cite:book}. C'était une simple
> histoire d'absence de % en fin de ligne...
> Voici une nouvelle version qui corrige le problème (à renommer en enc.bbx)
> !
> enc.txt
> https://github.com/Jean-Baptiste-Camps/biblatex-enc/files/46626/enc.txt
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Jean-Baptiste-Camps/biblatex-enc/issues/1#issuecomment-160418301
> .

## 

Adeline Adam
06 79 89 84 58
