### ISSUE TITLE
modifier \DefineBibliographyExtras

### ISSUE THREAD

**Issue by Enimie** [Jean-Baptiste-Camps/biblatex-enc#7]
Avec la nouvelle version de polyglossia, la définition de \DefineBibliographyExtras (l.79) ne fonctionne plus (en revanche il n'y a aucun problème avec babel)
Après test, cette nouvelle définition fonctionne:

```
\DefineBibliographyExtras{french}{%
\renewcommand*{\mkbibnamefamily}[1]{\textnohyphenation{#1}}%
}
```
Est-ce que tu pourrais l'intégrer?
Merci!

**Comment by Jean-Baptiste-Camps** [comment]
Fixed as well !

**Comment by Enimie** [comment]
Sorry, I made a mistake, the command is `\nohyphenation` and not `\textnohyphenation`, so:

```
\DefineBibliographyExtras{french}{%
\renewcommand*{\mkbibnamefamily}[1]{\nohyphenation{#1}}%
}
```
Could you fix it? 
Thank...
